[build]
  command = "pip install -r requirements.txt"
  functions = "functions"
  publish = "static"

[functions]
  directory = "functions"
  included_files = [
    "app.py",
    "config.py",
    "data/**",
    "utils/**",
    "templates/**"
  ]

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main/:splat"
  status = 200
