[build]
  command = "pip install -r requirements.txt"
  functions = "functions"
  publish = "static"

[functions]
  directory = "functions"
  included_files = ["templates/**", "data/**"]

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
